version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    image: narimt/car_price_dash:a2.6
    environment:
      - HOST=0.0.0.0
      - PORT=80
    ports:
      - 4000:80
    command: python code/app.py
