version: '3.9'

services:
  dash:
    image: your-dockerhub-username/ait-ml-dash:2023
    container_name: dash_car_app
    ports:
      - "80:80"
    environment:
      - HOST=0.0.0.0
      - PORT=80
    networks:
      - default
      - traefik_default

networks:
  default:
  traefik_default:
    external: true
